name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: satviewer
        uses: actions/checkout@v2
      - name: test
        run: ls -lia
